export const
    FETCH_USER_REQUEST = 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE = 'FETCH_USER_FAILURE',

    SET_USER_TOKEN = "SET_USER_TOKEN",
    SET_TOKEN_EXPIRATION_TIME = "SET_TOKEN_EXPIRATION_TIME",

    LOGIN_ERROR = "LOGIN_ERROR",
    LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
    LOGING_IN ="LOGING_IN",

    SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL",
    SIGNUP_ERROR = "SIGNUP_ERROR",
    SIGNING_UP = "SIGNING_UP"

