export const
    SET_USER = "SET_USER",
    SET_ERROR = "SET_ERROR",

    FETCH_USER_REQUEST = 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE = 'FETCH_USER_FAILURE',

    SET_USER_TOKEN = "SET_USER_TOKEN",
    SET_TOKEN_EXPIRATION_TIME = "SET_TOKEN_EXPIRATION_TIME",

    LOGIN_ERROR = "LOGIN_ERROR",
    LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
    LOGIN_REQUEST ="LOGIN_REQUEST",

    SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL",
    SIGNUP_ERROR = "SIGNUP_ERROR",
    SIGNUP_REQUEST = "SIGNUP_REQUEST",

    RESET_STATE = "RESET_STATE",

    LOGGED_OUT = "LOGGED_OUT"

